# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

"""Types for tool calling support in providers."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class ToolCall:
    """Represents a tool invocation request from the LLM.

    Attributes:
        id: Unique identifier for this tool call (used to match with results)
        name: Name of the tool to invoke
        arguments: Dictionary of arguments to pass to the tool
    """
    id: str
    name: str
    arguments: Dict[str, Any]


@dataclass
class ToolResult:
    """Result from executing a tool call.

    Attributes:
        tool_call_id: ID of the tool call this result corresponds to
        content: String content returned by the tool
        error: Error message if the tool execution failed (None if successful)
    """
    tool_call_id: str
    content: str
    error: Optional[str] = None


@dataclass
class GenerateResponse:
    """Enhanced response supporting both text generation and tool calls.

    This response type allows providers to return either:
    - Pure text responses (finish_reason="stop")
    - Tool call requests (finish_reason="tool_calls", tool_calls populated)
    - Partial responses due to length limits (finish_reason="length")

    Attributes:
        content: Text content generated by the model (may be empty if only tool calls)
        tool_calls: List of tool invocations requested by the model
        finish_reason: Why generation stopped ("stop", "tool_calls", "length")
    """
    content: str
    tool_calls: Optional[List[ToolCall]] = None
    finish_reason: str = "stop"

    def __post_init__(self):
        """Validate finish_reason and tool_calls consistency."""
        if self.finish_reason not in ("stop", "tool_calls", "length"):
            raise ValueError(
                f"finish_reason must be 'stop', 'tool_calls', or 'length', "
                f"got '{self.finish_reason}'"
            )
        if self.finish_reason == "tool_calls" and not self.tool_calls:
            raise ValueError(
                "finish_reason='tool_calls' requires non-empty tool_calls list"
            )
